---
# vars file for create-cluster
default_kubernetes_cni_weavenet_manifestUrl: "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

default_kubernetes_cni_flanel_manifestUrl: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
